In [2]:
import numpy as np
import pandas as pd
import sklearn

In [25]:
#reading the dataset
data=pd.read_csv("dataset.csv")
data

,id,age,sex,weight,hoursRunInAWeek,highHealWear,multipleJointPains,allignmentOfMidFoot,diabetes,cyanosis,burningSensationInPS,Tenderness,Status
0,1,21,0,55,7,0,0,0,0,0,0,0,0
1,2,14,0,57,7,0,0,0,0,0,0,1,0
2,3,21,0,51,12,0,0,0,0,0,1,0,0
3,4,23,0,42,8,0,0,0,0,0,1,1,0
4,5,12,0,62,9,0,0,0,0,1,0,0,0
5,6,12,0,50,10,0,0,0,0,1,0,1,0
6,7,10,0,40,6,0,0,0,0,1,1,0,0
7,8,15,0,63,12,0,0,0,0,1,1,1,0
8,9,57,0,59,2,0,0,0,1,0,0,0,1
9,10,59,0,52,3,0,0,0,1,0,0,1,0
10,11,51,0,52,0,0,0,0,1,0,1,0,1
11,12,53,0,53,1,0,0,0,1,0,1,1,0
12,13,42,0,59,2,0,0,0,1,1,0,0,0
13,14,57,0,67,2,0,0,0,1,1,0,1,1
14,15,48,0,62,0,0,0,0,1,1,1,0,1
15,16,52,0,51,3,0,0,0,1,1,1,1,0
16,17,16,0,53,1,0,0,1,0,0,0,0,0
17,18,13,0,66,0,0,0,2,0,0,0,0,0
18,19,20,0,58,3,0,0,1,0,0,0,1,0
19,20,24,0,59,3,0,0,2,0,0,0,1,0
20,21,22,0,56,0,0,0,1,0,0,1,0,0
21,22,25,0,55,1,0,0,2,0,0,1,0,0
22,23,25,0,50,2,0,0,1,0,0,1,1,0
23,24,17,0,54,1,0,0,2,0,0,1,1,0
24,25,17,0,57,1,0,0,1,0,1,0,0,0
25,26,11,0,65,0,0,0,2,0,1,0,0,0
26,27,10,0,70,0,0,0,1,0,1,0,1,0
27,28,12,0,55,0,0,0,2,0,1,0,1,0
28,29,21,0,65,2,0,0,1,0,1,1,0,0
29,30,21,0,69,0,0,0,2,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,355,31,1,65,1,1,1,1,0,0,0,1,0
355,356,34,1,54,3,1,1,2,0,0,0,1,0
356,357,28,1,58,3,1,1,1,0,0,1,0,0
357,358,28,1,58,2,1,1,2,0,0,1,0,0
358,359,43,1,61,0,1,1,1,0,0,1,1,0
359,360,50,1,56,0,1,1,2,0,0,1,1,1
360,361,32,1,50,3,1,1,1,0,1,0,0,0
361,362,36,1,63,1,1,1,2,0,1,0,0,0
362,363,36,1,55,3,1,1,1,0,1,0,1,0
363,364,42,1,63,2,1,1,2,0,1,0,1,0
364,365,46,1,63,0,1,1,1,0,1,1,0,0
365,366,50,1,61,1,1,1,2,0,1,1,0,0
366,367,37,1,58,1,1,1,1,0,1,1,1,0
367,368,34,1,66,1,1,1,2,0,1,1,1,0
368,369,45,1,72,2,1,1,1,1,0,0,0,0
369,370,57,1,79,0,1,1,2,1,0,0,0,1
370,371,54,1,76,0,1,1,1,1,0,0,1,1
371,372,52,1,64,3,1,1,2,1,0,0,1,0
372,373,49,1,69,3,1,1,1,1,0,1,0,0
373,374,59,1,64,1,1,1,2,1,0,1,0,0
374,375,59,1,78,0,1,1,1,1,0,1,1,1
375,376,55,1,85,1,1,1,2,1,0,1,1,1
376,377,52,1,64,0,1,1,1,1,1,0,0,1
377,378,52,1,64,3,1,1,2,1,1,0,0,0
378,379,60,1,76,1,1,1,1,1,1,0,1,1
379,380,52,1,79,1,1,1,2,1,1,0,1,1
380,381,41,1,69,3,1,1,1,1,1,1,0,0
381,382,48,1,84,3,1,1,2,1,1,1,0,0
382,383,49,1,85,0,1,1,1,1,1,1,1,1
383,384,56,1,83,1,1,1,2,1,1,1,1,1

In [11]:
#descripition of dataset
data
data.describe()
data.shape
data.head()
data.dtypes

id                      int64
age                     int64
sex                     int64
weight                  int64
hoursRunInAWeek         int64
highHealWear            int64
multipleJointPains      int64
allignmentOfMidFoot     int64
diabetes                int64
cyanosis                int64
burningSensationInPS    int64
Tenderness              int64
Status                  int64
dtype: object

In [10]:
#checking dataset contains any NAN values
data.isnull().values.any()
data.isnull().sum()

id                      0
age                     0
sex                     0
weight                  0
hoursRunInAWeek         0
highHealWear            0
multipleJointPains      0
allignmentOfMidFoot     0
diabetes                0
cyanosis                0
burningSensationInPS    0
Tenderness              0
Status                  0
dtype: int64

In [16]:
#from dataset by using classification selecting inputs and outputs
#selecting of input columns from the dataset
data_x=data[["age","weight","hoursRunInAWeek","highHealWear","multipleJointPains","allignmentOfMidFoot","diabetes","cyanosis","burningSensationInPS","Tenderness"]]

In [21]:
#disciription of input data
data_x.shape
data_x.describe()
data_x.dtypes
data_x.head()

,age,weight,hoursRunInAWeek,highHealWear,multipleJointPains,allignmentOfMidFoot,diabetes,cyanosis,burningSensationInPS,Tenderness
0,21,55,7,0,0,0,0,0,0,0
1,14,57,7,0,0,0,0,0,0,1
2,21,51,12,0,0,0,0,0,1,0
3,23,42,8,0,0,0,0,0,1,1
4,12,62,9,0,0,0,0,1,0,0

In [23]:
#selecting the output from the dataset
data_y=data.iloc[:,-1]
data_y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      1
9      0
10     1
11     0
12     0
13     1
14     1
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
354    0
355    0
356    0
357    0
358    0
359    1
360    0
361    0
362    0
363    0
364    0
365    0
366    0
367    0
368    0
369    1
370    1
371    0
372    0
373    0
374    1
375    1
376    1
377    0
378    1
379    1
380    0
381    0
382    1
383    1
Name: Status, Length: 384, dtype: int64

In [24]:
#disciription of output data
data_y.shape
data_y.describe()
data_y.dtypes
data_y.head()

0    0
1    0
2    0
3    0
4    0
Name: Status, dtype: int64

In [30]:
#checking no.of positive and negative results from output
data["Status"].value_counts()
len(data.loc[data["Status"]==1])
data.groupby("Status").size()

Status
0    279
1    105
dtype: int64

In [46]:
# checking no.of zeros in both input and ouputs
# for inputs
print(" the no.of zeros in age :{}".format(len(data.loc[data["age"]]==0)))
print(" the no.of zeros in weight:{}".format(len(data.loc[data["weight"]]==0)))
print(" the no.of zeros in hoursRunInAWeek :{}".format(len(data.loc[data["hoursRunInAWeek"]]==0)))
print(" the no.of zeros in highHealWear :{}".format(len(data.loc[data["highHealWear"]]==0)))
print(" the no.of zeros in multipleJointPains :{}".format(len(data.loc[data["multipleJointPains"]]==0)))                                           
print(" the no.of zeros in allignmentOfMidFoot :{}".format(len(data.loc[data["allignmentOfMidFoot"]]==0)))
print(" the no.of zeros in diabetes :{}".format(len(data.loc[data["diabetes"]]==0)))
print(" the no.of zeros in cyanosis :{}".format(len(data.loc[data["cyanosis"]]==0)
#print(" the no.of zeros in  burningSensationInPS:{}".format(len(data.loc[data[" burningSensationInPS"]]==0)
print(" the no.of zeros in Tenderness :{}".format(len(data.loc[data["Tenderness"]]==0)))

SyntaxError: unexpected EOF while parsing (<ipython-input-46-4a65511c5ace>, line 12)

In [45]:
data_x.head()

,age,weight,hoursRunInAWeek,highHealWear,multipleJointPains,allignmentOfMidFoot,diabetes,cyanosis,burningSensationInPS,Tenderness
0,21,55,7,0,0,0,0,0,0,0
1,14,57,7,0,0,0,0,0,0,1
2,21,51,12,0,0,0,0,0,1,0
3,23,42,8,0,0,0,0,0,1,1
4,12,62,9,0,0,0,0,1,0,0

In [47]:
print(" the no.of zeros in age :{}".format(len(data.loc[data["age"]]==0)))

 the no.of zeros in age :384

In [48]:
print(" the no.of zeros in weight:{}".format(len(data.loc[data["weight"]]==0)))

 the no.of zeros in weight:384

In [49]:
print(" the no.of zeros in hoursRunInAWeek :{}".format(len(data.loc[data["hoursRunInAWeek"]]==0)))

 the no.of zeros in hoursRunInAWeek :384

In [50]:
print(" the no.of zeros in highHealWear :{}".format(len(data.loc[data["highHealWear"]]==0)))

 the no.of zeros in highHealWear :384

In [51]:
print(" the no.of zeros in multipleJointPains :{}".format(len(data.loc[data["multipleJointPains"]]==0)))

 the no.of zeros in multipleJointPains :384

In [52]:
print(" the no.of zeros in allignmentOfMidFoot :{}".format(len(data.loc[data["allignmentOfMidFoot"]]==0)))

 the no.of zeros in allignmentOfMidFoot :384

In [53]:
print(" the no.of zeros in diabetes :{}".format(len(data.loc[data["diabetes"]]==0)))

 the no.of zeros in diabetes :384

In [55]:
print(" the no.of zeros in cyanosis :{}".format(len(data.loc[data["cyanosis"]]==0)))

 the no.of zeros in cyanosis :384

In [58]:
print(" the no.of zeros in  burningSensationInPS:{}".format(len(data.loc[data["burningSensationInPS"]]==0)))

 the no.of zeros in  burningSensationInPS:384

In [59]:
print(" the no.of zeros in Tenderness :{}".format(len(data.loc[data["Tenderness"]]==0)))

 the no.of zeros in Tenderness :384

In [60]:
#for ourtput
print(" the no.of zeros in status :{}".format(len(data.iloc[data["Status"]]==0)))

 the no.of zeros in status :384

In [62]:
#traing the input and output values
from sklearn.model_selection import train_test_split
feature_columns = ['age','weight','hoursRunInAWeek','highHealWear','multipleJointPains','allignmentOfMidFoot','diabetes','cyanosis','burningSensationInPS','Tenderness']
predicted_class = ['Status']
X = data[feature_columns].values
y = data[predicted_class].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=10)

In [66]:
print("number of rows missing age: {0}".format(len(data.loc[data['age'] == 0])))
print("number of rows missing weight: {0}".format(len(data.loc[data['weight'] == 0])))
print("number of rows missing hoursRunInAWeek: {0}".format(len(data.loc[data['hoursRunInAWeek'] == 0])))
print("number of rows missing highHealWear: {0}".format(len(data.loc[data['highHealWear'] == 0])))
print("number of rows missing multipleJointPains: {0}".format(len(data.loc[data['multipleJointPains'] == 0])))
print("number of rows missing allignmentOfMidFoot: {0}".format(len(data.loc[data['allignmentOfMidFoot'] == 0])))
print("number of rows missing diabetes: {0}".format(len(data.loc[data['diabetes'] == 0])))
print("number of rows missing cyanosis: {0}".format(len(data.loc[data['cyanosis'] == 0])))
print("number of rows missing burningSensationInPS: {0}".format(len(data.loc[data['burningSensationInPS'] == 0])))
print("number of rows missing Tenderness: {0}".format(len(data.loc[data['Tenderness'] == 0])))

number of rows missing age: 0
number of rows missing weight: 0
number of rows missing hoursRunInAWeek: 86
number of rows missing highHealWear: 192
number of rows missing multipleJointPains: 192
number of rows missing allignmentOfMidFoot: 128
number of rows missing diabetes: 192
number of rows missing cyanosis: 192
number of rows missing burningSensationInPS: 192
number of rows missing Tenderness: 192

In [68]:
#converting the zeros into mean values for the prensented rows and column
from sklearn.preprocessing import Imputer
fill_values = Imputer(missing_values=0, strategy="mean", axis=0)
X_train = fill_values.fit_transform(X_train)
X_test = fill_values.fit_transform(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [72]:
#applying algorithm for trained datas
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB(priors=None, var_smoothing=1e-09)

In [75]:
predict_train_data = gnb.predict(X_test)
predict_train_data

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1], dtype=int64)

In [78]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predict_train_data))

0.8103448275862069

In [81]:
#creating module using pickle
import pickle
with open("module.pickle","wb") as f:
    pickle.dump(gnb,f)
with open("module.pickle","rb") as f:
    model=pickle.load(f)

In [82]:
model.predict([[1,2,3,4,5,6,7,8,9,2]])

array([0], dtype=int64)

In [83]:
Filename = "plan.sav"
pickle.dump(gnb,open(Filename,'wb'))